[project]
name = "my-gymnasium"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gymnasium[classic-control]>=1.2.0",
    "tqdm>=4.67.1",
]
